### ISSUE TITLE
Multiple Field Groups

### ISSUE THREAD

**Issue by Wemago** [advancedforms/advanced-forms#23]
Just tested with multiple field groups, why do you merge fields to one field group? What if I want to show it by field groups with its specific title?

Ex.
Field Group: Details
- Title
- Description

Field Group: Location
- Address
- Coordinates

Also it would be nice if we could reorder fields and / or fields groups, you are ordering alphabetically.
Instead of having hard coded the fields metabox, why not use repeater or group field from ACF?

Something like this:
![idea_af_2](https://user-images.githubusercontent.com/135612/35577822-eaac2a96-05d1-11e8-8432-cc213391a231.jpg)

**Comment by Fabianlindfors** [comment]
Hi!

Merging the field group was a design decision I made from the beginning as I didn't want the field group names etc. to influence the form. Basically I only wanted the fields to matter but I see what you mean with the titled field groups, that would be a nice feature if I can make it work in a simple way.  Group fields are a nice alternative until then.

It is actually possible to rearrange the field groups although I'll admit it isn't too intuitive. ACF has a setting on all field groups called "Order no." which my plugin respects. This defaults to 0 which I'm guessing makes ACF fall back to alphabetic ordering. Introducing a simpler way to rearrange the groups would be nice but I like to respect the settings ACF has as far as possible, which makes it harder to implement my own solution.

Regarding the fields metabox it wasn't never really meant to contain more settings for the form but simply to serve as a reference on what fields the form has. I prefer to leave as much to ACF as possible, especially in regards to fields. This is in order to decrease complexity and the risk of breaking compatibility.

Thanks for you great suggestions, much appreciated!
