### ISSUE TITLE
Edit post of current user

### ISSUE THREAD

**Issue by MPHood** [advancedforms/advanced-forms#66]
Is there a shortcode (or other way) to let logged in users only edit their own (custom) posts created with your Plugin? 
  
The shortcode using "current" does not seem to do that.

**Comment by fabianlindfors** [comment]
Hi!

There currently is no built-in functionality to do this filtering. Mostly because it would require my plugin to display some kind of error message which would be a bit hard to add without making the UI more complex.

I usually recommend people to write a little bit of code in cases like these. I'd love to give you some pointers if you need.
