### ISSUE TITLE
af_get_field not working with sub fields inside "Group" field who is inside a "Group" field

### ISSUE THREAD

**Issue by cedche99** [advancedforms/advanced-forms#76]
I commented on this problem https://github.com/advancedforms/advanced-forms/issues/35 but I prefer to create a new one.

----
Hi,

I think there is a problem when you have a group that owns another group.

Example : 

1 ACF : 
![image](https://user-images.githubusercontent.com/12508260/68768678-489b9800-0623-11ea-9b16-134c05e1f2e7.png)

who has a acf dog (see 2 ACF)

2 ACF : 
![image](https://user-images.githubusercontent.com/12508260/68768779-75e84600-0623-11ea-9467-00d7fdd4c1a2.png)

Who has a acf owner (see 3 ACF)

3 ACF : 
![image](https://user-images.githubusercontent.com/12508260/68768831-92847e00-0623-11ea-90e8-acc309ec6289.png)

If i do : 

`af_get_field("civilite")` => Return false

When i see the data : 
![image](https://user-images.githubusercontent.com/12508260/68769019-e55e3580-0623-11ea-8117-1ce47856e06f.png)

We do not go through the group

to correct I add: 

`if ( $sub_field_name == $field_key_or_name ) {
					return $sub_field_value;
				}elseif( $sub_field_name == 'groupe'){
					foreach ($sub_field_value as $sub_field_name_2 => $sub_field_value_2) {
						if ( $sub_field_name_2 == $field_key_or_name ) {
							return $sub_field_value_2;
						}
					}
				}`

![image](https://user-images.githubusercontent.com/12508260/68769620-ea6fb480-0624-11ea-8712-92abf8d0bd29.png)

for the future it would not be judicious to use the indentifiants and not the names like key?

**Comment by fabianlindfors** [comment]
Hi!

As you've noticed `af_get_field` won't go down nested groups. This is because there could be naming collisions of fields causing unexpected behavior.

The way ACF handles this makes it a bit hard. Because these fields are considered sub fields you have to go through the parent field to find its value. I would recommend doing something like this to fetch a sub field of a group: `af_get_field( 'groupe' )[ 'civilite' ]`.

I've been thinking of ways to make this easier for a while but haven't come up with a good solution yet. Sorry about that!
